define SIXRD_ENABLE
@$(call MESSAGE,"Enabling kernel 6rd feature")
@$(call KCONFIG_ENABLE_OPT,CONFIG_IPV6_SIT,$(LINUX_CONFIG))
@$(call KCONFIG_ENABLE_OPT,CONFIG_IPV6_SIT_6RD,$(LINUX_CONFIG))
endef

LINUX_ADDONS += $(if $(BR2_SUPPORT_6RD),SIXRD_ENABLE,)
