#############################################################
#
# jansson
#
#############################################################

JANSSON_VERSION = 2.13.1
JANSSON_SITE = $(DLINK_STORAGE)
JANSSON_SOURCE = jansson-$(JANSSON_VERSION).tar.gz
JANSSON_LICENSE = MIT
JANSSON_LICENSE_FILES = LICENSE
JANSSON_INSTALL_STAGING = YES
JANSSON_SUPPORTS_IN_SOURCE_BUILD = NO

JANSSON_OPT := \
  -DJANSSON_BUILD_DOCS=OFF \
  -DJANSSON_BUILD_SHARED_LIBS=ON \
  -DJANSSON_EXAMPLES=OFF \
  -DJANSSON_WITHOUT_TESTS=ON

JANSSON_CONF_OPT += $(JANSSON_OPT)
HOST_JANSSON_CONF_OPT += $(JANSSON_OPT)

ifeq ($(BR2_USER_DEBUG), y)
  JANSSON_CONF_OPT += -DCMAKE_BUILD_TYPE=Debug
endif

HOST_JANSSON_CONF_OPT += -DCMAKE_BUILD_TYPE=Debug

$(eval $(call CMAKETARGETS))
$(eval $(call CMAKETARGETS,host))
