#############################################################
#
# hostapd
#
#############################################################

HOSTAPD_VERSION = $(call qstrip,$(BR2_PACKAGE_HOSTAPD_VERSION))
HOSTAPD_SITE = $(DLINK_GIT_STORAGE)/hostapd

HOSTAPD_SUBDIR = hostapd
HOSTAPD_CONFIG = $(HOSTAPD_DIR)/$(HOSTAPD_SUBDIR)/.config

HOSTAPD_LICENSE = BSD-3-Clause
HOSTAPD_LICENSE_FILES = README

HOSTAPD_DEPENDENCIES += libnl openssl
HOSTAPD_CFLAGS=$(TARGET_CFLAGS) -I$(STAGING_DIR)/include/libnl3/
HOSTAPD_LDFLAGS=$(TARGET_LDFLAGS)
HOSTAPD_MAKE_ENV=$(TARGET_MAKE_ENV) CONFIG_NO_GITVER=y

HOSTAPD_CONFIG_EDITS =
HOSTAPD_CONFIG_ENABLE = CONFIG_IEEE80211N CONFIG_LIBNL32
HOSTAPD_CONFIG_DISABLE =

ifneq ($(BR2_PACKAGE_LIBTOMMATH),y)
HOSTAPD_CONFIG_ENABLE += CONFIG_INTERNAL_LIBTOMMATH
endif

ifeq ($(BR2_SUPPORT_WIFI_AC),y)
HOSTAPD_CONFIG_ENABLE += CONFIG_IEEE80211AC
endif

ifeq ($(BR2_SUPPORT_WIFI_AX),y)
HOSTAPD_CONFIG_ENABLE += CONFIG_IEEE80211AX
endif

ifeq ($(BR2_PACKAGE_HOSTAPD_ACS),y)
HOSTAPD_CONFIG_ENABLE += CONFIG_ACS
endif

ifeq ($(BR2_PACKAGE_HOSTAPD_WPS),y)
HOSTAPD_CONFIG_ENABLE += CONFIG_WPS
endif

ifeq ($(BR2_PACKAGE_HOSTAPD_WPA3),y)
HOSTAPD_CONFIG_SET += CONFIG_SAE
endif

ifeq ($(BR2_PACKAGE_HOSTAPD_WNM),y)
HOSTAPD_CONFIG_ENABLE += CONFIG_WNM
endif

ifeq ($(BR2_PACKAGE_HOSTAPD_VLAN),)
HOSTAPD_CONFIG_ENABLE += CONFIG_NO_VLAN
endif

ifeq ($(BR2_PACKAGE_HOSTAPD_VLAN_DYNAMIC),y)
HOSTAPD_CONFIG_ENABLE += CONFIG_FULL_DYNAMIC_VLAN
endif

ifeq ($(BR2_PACKAGE_HOSTAPD_VLAN_NETLINK),y)
HOSTAPD_CONFIG_ENABLE += CONFIG_VLAN_NETLINK
endif

ifeq ($(BR2_PACKAGE_HOSTAPD_DEBUG_SYSLOG),y)
HOSTAPD_CONFIG_ENABLE += CONFIG_DEBUG_SYSLOG
endif

# D-Link system daemon
ifeq ($(BR2_DSYSINIT),y)
HOSTAPD_DEPENDENCIES += deuteron_framework
HOSTAPD_LDFLAGS += -ld_service_notify -Wl,-rpath-link $(STAGING_DIR)/usr/lib
endif

define HOSTAPD_CONFIGURE_CMDS
	cp $(@D)/hostapd/defconfig $(HOSTAPD_CONFIG)
	sed -i $(patsubst %,-e 's/^#\(%=\)/\1/',$(HOSTAPD_CONFIG_ENABLE)) \
		$(patsubst %,-e 's/^\(%=\)/#\1/',$(HOSTAPD_CONFIG_DISABLE)) \
		$(patsubst %,-e '1i%=y',$(HOSTAPD_CONFIG_SET)) \
		$(patsubst %,-e %,$(HOSTAPD_CONFIG_EDITS)) \
		$(HOSTAPD_CONFIG)
endef

define HOSTAPD_BUILD_CMDS
	$(HOSTAPD_MAKE_ENV) CFLAGS="$(HOSTAPD_CFLAGS)" \
		LDFLAGS="$(HOSTAPD_LDFLAGS)" \
		$(MAKE) CC="$(TARGET_CC)" -C $(@D)/$(HOSTAPD_SUBDIR)
endef

define HOSTAPD_INSTALL_TARGET_CMDS
	$(INSTALL) -m 0755 -D $(@D)/$(HOSTAPD_SUBDIR)/hostapd \
		$(TARGET_DIR)/usr/sbin/hostapd
	$(INSTALL) -m 0755 -D $(@D)/$(HOSTAPD_SUBDIR)/hostapd_cli \
		$(TARGET_DIR)/usr/bin/hostapd_cli
endef

define HOSTAPD_CLEAN_CMDS
    $(MAKE) -C $(@D)/$(HOSTAPD_SUBDIR) clean
endef

$(eval $(call GENTARGETS))
