################################################################################
#
# wpa_supplicant
#
################################################################################

WPA_SUPPLICANT_VERSION = $(call qstrip,$(BR2_PACKAGE_WPA_SUPPLICANT_VERSION))
WPA_SUPPLICANT_REPOSITORY = $(call qstrip,$(BR2_PACKAGE_WPA_SUPPLICANT_REPOSITORY))
WPA_SUPPLICANT_SITE = $(DLINK_GIT_STORAGE)/$(WPA_SUPPLICANT_REPOSITORY)

WPA_SUPPLICANT_SUBDIR = wpa_supplicant
WPA_SUPPLICANT_CONFIG = $(WPA_SUPPLICANT_DIR)/$(WPA_SUPPLICANT_SUBDIR)/.config
WPA_SUPPLICANT_INSTALL_STAGING = YES

WPA_SUPPLICANT_LICENSE = BSD-3-Clause
WPA_SUPPLICANT_LICENSE_FILES = README

WPA_SUPPLICANT_DEPENDENCIES += libnl openssl
WPA_SUPPLICANT_CFLAGS = $(TARGET_CFLAGS) -I$(STAGING_DIR)/include/libnl3/
WPA_SUPPLICANT_LDFLAGS = $(TARGET_LDFLAGS)
WPA_SUPPLICANT_MAKE_ENV = $(TARGET_MAKE_ENV) CONFIG_NO_GITVER=y

WPA_SUPPLICANT_CONFIG_EDITS =
WPA_SUPPLICANT_CONFIG_ENABLE = CONFIG_IEEE80211N CONFIG_LIBNL32
WPA_SUPPLICANT_CONFIG_DISABLE = \
	CONFIG_CTRL_IFACE_DBUS_NEW \
	CONFIG_CTRL_IFACE_DBUS_INTRO \
	CONFIG_SMARTCARD \
	CONFIG_HS20 \
	CONFIG_INTERWORKING \
	CONFIG_DEBUG_FILE \
	CONFIG_AP \
	CONFIG_P2P \
	CONFIG_WIFI_DISPLAY \
	CONFIG_MACSEC \
	CONFIG_DRIVER_MACSEC_LINUX \
	CONFIG_IEEE80211R \
	CONFIG_PKCS12 \
	CONFIG_DPP

ifneq ($(BR2_PACKAGE_WPA_SUPPLICANT_DRIVER_NL80211),y)
WPA_SUPPLICANT_CONFIG_DISABLE += CONFIG_DRIVER_NL80211
endif

ifneq ($(BR2_PACKAGE_WPA_SUPPLICANT_DRIVER_WEXT),y)
WPA_SUPPLICANT_CONFIG_DISABLE += CONFIG_DRIVER_WEXT
endif

ifneq ($(BR2_PACKAGE_WPA_SUPPLICANT_DRIVER_WIRED),y)
WPA_SUPPLICANT_CONFIG_DISABLE += CONFIG_DRIVER_WIRED
endif

ifneq ($(BR2_PACKAGE_LIBTOMMATH),y)
WPA_SUPPLICANT_CONFIG_ENABLE += CONFIG_INTERNAL_LIBTOMMATH
endif

ifeq ($(BR2_SUPPORT_WIFI_AC),y)
WPA_SUPPLICANT_CONFIG_ENABLE += CONFIG_IEEE80211AC
endif

ifeq ($(BR2_SUPPORT_WIFI_AX),y)
WPA_SUPPLICANT_CONFIG_SET += CONFIG_IEEE80211AX
endif

ifneq ($(BR2_PACKAGE_WPA_SUPPLICANT_EAP),y)
WPA_SUPPLICANT_CONFIG_DISABLE += \
	CONFIG_IEEE8021X_EAPOL \
	CONFIG_EAP_MD5 \
	CONFIG_EAP_MSCHAPV2 \
	CONFIG_EAP_TLS \
	CONFIG_EAP_PEAP \
	CONFIG_EAP_TTLS \
	CONFIG_EAP_FAST \
	CONFIG_EAP_TEAP \
	CONFIG_EAP_GTC \
	CONFIG_EAP_OTP \
	CONFIG_EAP_SIM \
	CONFIG_EAP_PSK \
	CONFIG_EAP_PWD \
	CONFIG_EAP_PAX \
	CONFIG_EAP_LEAP \
	CONFIG_EAP_AKA \
	CONFIG_EAP_AKA_PRIME \
	CONFIG_EAP_SAKE \
	CONFIG_EAP_GPSK \
	CONFIG_EAP_GPSK_SHA256 \
	CONFIG_EAP_TNC \
	CONFIG_EAP_IKEV2
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_WPS),y)
WPA_SUPPLICANT_CONFIG_ENABLE += CONFIG_WPS
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_WPA3),y)
WPA_SUPPLICANT_CONFIG_ENABLE += CONFIG_SAE
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_DEBUG_SYSLOG),y)
WPA_SUPPLICANT_CONFIG_ENABLE += CONFIG_DEBUG_SYSLOG
endif

# D-Link system daemon
ifeq ($(BR2_DSYSINIT),y)
WPA_SUPPLICANT_DEPENDENCIES += deuteron_framework
WPA_SUPPLICANT_LDFLAGS += -ld_service_notify -Wl,-rpath-link $(STAGING_DIR)/usr/lib
endif

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_WPA_CLIENT_SO),y)
WPA_SUPPLICANT_CONFIG_SET += CONFIG_BUILD_WPA_CLIENT_SO
define WPA_SUPPLICANT_INSTALL_WPA_CLIENT_SO
	$(INSTALL) -m 0644 -D $(@D)/$(WPA_SUPPLICANT_SUBDIR)/libwpa_client.so \
		$(TARGET_DIR)/usr/lib/libwpa_client.so
	$(INSTALL) -m 0644 -D $(@D)/src/common/wpa_ctrl.h \
		$(TARGET_DIR)/usr/include/wpa_ctrl.h
endef
define WPA_SUPPLICANT_INSTALL_STAGING_WPA_CLIENT_SO
	$(INSTALL) -m 0644 -D $(@D)/$(WPA_SUPPLICANT_SUBDIR)/libwpa_client.so \
		$(STAGING_DIR)/usr/lib/libwpa_client.so
	$(INSTALL) -m 0644 -D $(@D)/src/common/wpa_ctrl.h \
		$(STAGING_DIR)/usr/include/wpa_ctrl.h
endef
endif

define WPA_SUPPLICANT_CONFIGURE_CMDS
	cp $(@D)/wpa_supplicant/defconfig $(WPA_SUPPLICANT_CONFIG)
	sed -i $(patsubst %,-e 's/^#\(%=\)/\1/',$(WPA_SUPPLICANT_CONFIG_ENABLE)) \
		$(patsubst %,-e 's/^\(%=\)/#\1/',$(WPA_SUPPLICANT_CONFIG_DISABLE)) \
		$(patsubst %,-e '1i%=y',$(WPA_SUPPLICANT_CONFIG_SET)) \
		$(patsubst %,-e %,$(WPA_SUPPLICANT_CONFIG_EDITS)) \
		$(WPA_SUPPLICANT_CONFIG)
endef

define WPA_SUPPLICANT_BUILD_CMDS
	$(WPA_SUPPLICANT_MAKE_ENV) CFLAGS="$(WPA_SUPPLICANT_CFLAGS)" \
		LDFLAGS="$(WPA_SUPPLICANT_LDFLAGS)" \
		$(MAKE) CC="$(TARGET_CC)" -C $(@D)/$(WPA_SUPPLICANT_SUBDIR)
endef

ifeq ($(BR2_PACKAGE_WPA_SUPPLICANT_PASSPHRASE),y)
define WPA_SUPPLICANT_INSTALL_PASSPHRASE
	$(INSTALL) -m 0755 -D $(@D)/$(WPA_SUPPLICANT_SUBDIR)/wpa_passphrase \
		$(TARGET_DIR)/usr/sbin/wpa_passphrase
endef
endif

define WPA_SUPPLICANT_INSTALL_STAGING_CMDS
	$(WPA_SUPPLICANT_INSTALL_STAGING_WPA_CLIENT_SO)
endef

define WPA_SUPPLICANT_INSTALL_TARGET_CMDS
	$(INSTALL) -m 0755 -D $(@D)/$(WPA_SUPPLICANT_SUBDIR)/wpa_supplicant \
		$(TARGET_DIR)/usr/sbin/wpa_supplicant
	$(INSTALL) -m 0755 -D $(@D)/$(WPA_SUPPLICANT_SUBDIR)/wpa_cli \
		$(TARGET_DIR)/usr/sbin/wpa_cli
	$(WPA_SUPPLICANT_INSTALL_PASSPHRASE)
	$(WPA_SUPPLICANT_INSTALL_WPA_CLIENT_SO)
endef

define WPA_SUPPLICANT_CLEAN_CMDS
	$(MAKE) -C $(@D)/$(WPA_SUPPLICANT_SUBDIR) clean
endef

$(eval $(call GENTARGETS))
